name: pumaguard-tensorflow
base: core24
adopt-info: pumaguard-tensorflow
license: Apache-2.0
source-code: https://github.com/PEEC-Nature-Youth-Group/pumaguard-tensorflow-snap
website: https://pumaguard.rtfd.io/
grade: stable
confinement: strict
contact: nicolasbock@gmail.com

summary: PumaGuard is a machine-learning based Puma mitigation solution
description: |
  The goal of this project is to accurately classify images based on the
  presence of mountain lions. This can have applications in wildlife
  monitoring, research, and conservation efforts. The model is trained on a
  labeled dataset and validated using a separate set of images.

slots:
  tensorflow:
    interface: content
    source:
      read:
        - $SNAP/lib
        - $SNAP/usr/lib

apps:
  pumaguard-tensorflow:
    command: bin/pumaguard-tensorflow

parts:
  pumaguard-tensorflow:
    plugin: poetry
    source: .
    build-packages:
      - git
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags)
      poetry --version
